# Generated by Django 5.2.7 on 2026-04-24 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cliente',
            options={'ordering': ['apellidos', 'nombres'], 'verbose_name': 'Cliente', 'verbose_name_plural': 'Clientes'},
        ),
        migrations.RenameField(
            model_name='cliente',
            old_name='creado_en',
            new_name='fecha_registro',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='correo',
        ),
        migrations.AddField(
            model_name='cliente',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='estado',
            field=models.IntegerField(choices=[(1, 'Activo'), (9, 'De baja')], default=1),
        ),
        migrations.AddField(
            model_name='cliente',
            name='nro_doc',
            field=models.CharField(default='00000000', max_length=15, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cliente',
            name='tipo_doc',
            field=models.CharField(choices=[('DNI', 'DNI'), ('RUC', 'RUC'), ('PAS', 'Pasaporte')], default='DNI', max_length=3),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='apellidos',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='direccion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='nombres',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='telefono',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterModelTable(
            name='cliente',
            table='clientes',
        ),
    ]
